[project]
site_name = "Upstream Data - Docs"
site_description = "Documentation for Upstream Data hardware."
site_author = "Upstream Data"
site_url = "https://upstreamdata.github.io/"
copyright = """
Copyright &copy; 2026 Upstream Data Inc
"""
use_directory_urls = true
nav = [
    { "Initial Setup" = "guides/initial-setup.md" },
    { "Maintenance" = "guides/maintenance.md" },
    { "LoadSyncâ„¢" = "guides/loadsync.md" },
    { "Contact Us" = "guides/contact.md" }
]
extra_css = ["stylesheets/images.css"]
markdown_extensions = [
    "attr_list",
    "admonition",
    "pymdownx.details",
    "pymdownx.superfences",
    {"pymdownx.tabbed" = {alternate_style = true, slugify = {case = "lower"}}},
    "md_in_html",
    "pymdownx.blocks.caption",
    "pymdownx.snippets",
    "abbr",
    {"pymdownx.tasklist" = {custom_checkbox = true}},
    {"toc" = {permalink = true}},
    {"pymdownx.emoji" = {emoji_index = "zensical.extensions.emoji.twemoji", emoji_generator = "zensical.extensions.emoji.to_svg"}},
    "tables",
    "pymdownx.caret",
    "pymdownx.tilde",
    "pymdownx.mark",
]

[project.theme]
favicon = "logo/logo.svg"
logo = "logo/logo.svg"
language = "en"

features = [
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    "toc.integrate",
    "content.tooltips",
    "content.tabs.link",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[[project.extra.social]]
icon = "lucide/mail"
name = "Contact Support"
link = "mailto:support@upstreamdata.com"

[[project.extra.social]]
icon = "lucide/globe"
name = "Website"
link = "upstreamdata.com"
